donnyji/donnyji/urls.py
from django.contrib import admin
from django.apps import apps
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(apps.get_app_config('oscar').urls[0])),
]

donnyji/oscar/apps/address/models.py
from oscar.apps.address.abstract_models import (
    AbstractCountry, AbstractUserAddress)
from oscar.core.loading import is_model_registered

__all__ = []


if not is_model_registered('address', 'UserAddress'):
    class UserAddress(AbstractUserAddress):
        pass

    __all__.append('UserAddress')


if not is_model_registered('address', 'Country'):
    class Country(AbstractCountry):
        pass

    __all__.append('Country')

donnyji/oscar/apps/analytics/models.py
from oscar.apps.analytics.abstract_models import (
    AbstractProductRecord, AbstractUserProductView,
    AbstractUserRecord, AbstractUserSearch)
from oscar.core.loading import is_model_registered

__all__ = []


if not is_model_registered('analytics', 'ProductRecord'):
    class ProductRecord(AbstractProductRecord):
        pass

    __all__.append('ProductRecord')


if not is_model_registered('analytics', 'UserRecord'):
    class UserRecord(AbstractUserRecord):
        pass

    __all__.append('UserRecord')


if not is_model_registered('analytics', 'UserProductView'):
    class UserProductView(AbstractUserProductView):
        pass

    __all__.append('UserProductView')


if not is_model_registered('analytics', 'UserSearch'):
    class UserSearch(AbstractUserSearch):
        pass

    __all__.append('UserSearch')

donnyji/oscar/apps/basket/models.py
from oscar.apps.basket.abstract_models import (
    AbstractBasket, AbstractLine, AbstractLineAttribute)
from oscar.core.loading import is_model_registered

__all__ = [
    'InvalidBasketLineError',
]


class InvalidBasketLineError(Exception):
    pass


if not is_model_registered('basket', 'Basket'):
    class Basket(AbstractBasket):
        pass

    __all__.append('Basket')


if not is_model_registered('basket', 'Line'):
    class Line(AbstractLine):
        pass

    __all__.append('Line')


if not is_model_registered('basket', 'LineAttribute'):
    class LineAttribute(AbstractLineAttribute):
        pass

    __all__.append('LineAttribute')

donnyji/oscar/apps/catalogue/models.py
"""
Vanilla product models
"""
from oscar.apps.catalogue.abstract_models import *  # noqa
from oscar.core.loading import is_model_registered

__all__ = ['ProductAttributesContainer']


if not is_model_registered('catalogue', 'ProductClass'):
    class ProductClass(AbstractProductClass):
        pass

    __all__.append('ProductClass')


if not is_model_registered('catalogue', 'Category'):
    class Category(AbstractCategory):
        pass

    __all__.append('Category')


if not is_model_registered('catalogue', 'ProductCategory'):
    class ProductCategory(AbstractProductCategory):
        pass

    __all__.append('ProductCategory')


if not is_model_registered('catalogue', 'Product'):
    class Product(AbstractProduct):
        pass

    __all__.append('Product')


if not is_model_registered('catalogue', 'ProductRecommendation'):
    class ProductRecommendation(AbstractProductRecommendation):
        pass

    __all__.append('ProductRecommendation')


if not is_model_registered('catalogue', 'ProductAttribute'):
    class ProductAttribute(AbstractProductAttribute):
        pass

    __all__.append('ProductAttribute')


if not is_model_registered('catalogue', 'ProductAttributeValue'):
    class ProductAttributeValue(AbstractProductAttributeValue):
        pass

    __all__.append('ProductAttributeValue')


if not is_model_registered('catalogue', 'AttributeOptionGroup'):
    class AttributeOptionGroup(AbstractAttributeOptionGroup):
        pass

    __all__.append('AttributeOptionGroup')


if not is_model_registered('catalogue', 'AttributeOption'):
    class AttributeOption(AbstractAttributeOption):
        pass

    __all__.append('AttributeOption')


if not is_model_registered('catalogue', 'Option'):
    class Option(AbstractOption):
        pass

    __all__.append('Option')


if not is_model_registered('catalogue', 'ProductImage'):
    class ProductImage(AbstractProductImage):
        pass

    __all__.append('ProductImage')

donnyji/oscar/apps/catalogue/reviews/models.py
from oscar.apps.catalogue.reviews.abstract_models import (
    AbstractProductReview, AbstractVote)
from oscar.core.loading import is_model_registered

if not is_model_registered('reviews', 'ProductReview'):
    class ProductReview(AbstractProductReview):
        pass


if not is_model_registered('reviews', 'Vote'):
    class Vote(AbstractVote):
        pass

donnyji/oscar/apps/customer/models.py
from oscar.apps.customer import abstract_models
from oscar.core.loading import is_model_registered

__all__ = []


if not is_model_registered('customer', 'Email'):
    class Email(abstract_models.AbstractEmail):
        pass

    __all__.append('Email')


if not is_model_registered('customer', 'CommunicationEventType'):
    class CommunicationEventType(
            abstract_models.AbstractCommunicationEventType):
        pass

    __all__.append('CommunicationEventType')


if not is_model_registered('customer', 'Notification'):
    class Notification(abstract_models.AbstractNotification):
        pass

    __all__.append('Notification')


if not is_model_registered('customer', 'ProductAlert'):
    class ProductAlert(abstract_models.AbstractProductAlert):
        pass

    __all__.append('ProductAlert')

donnyji/oscar/apps/offer/models.py
from oscar.apps.offer.abstract_models import (
    AbstractBenefit, AbstractCondition, AbstractConditionalOffer,
    AbstractRange, AbstractRangeProduct, AbstractRangeProductFileUpload)
from oscar.apps.offer.results import (
    SHIPPING_DISCOUNT, ZERO_DISCOUNT, BasketDiscount, PostOrderAction,
    ShippingDiscount)
from oscar.core.loading import is_model_registered

__all__ = [
    'BasketDiscount', 'ShippingDiscount', 'PostOrderAction',
    'SHIPPING_DISCOUNT', 'ZERO_DISCOUNT'
]


if not is_model_registered('offer', 'ConditionalOffer'):
    class ConditionalOffer(AbstractConditionalOffer):
        pass

    __all__.append('ConditionalOffer')


if not is_model_registered('offer', 'Benefit'):
    class Benefit(AbstractBenefit):
        pass

    __all__.append('Benefit')


if not is_model_registered('offer', 'Condition'):
    class Condition(AbstractCondition):
        pass

    __all__.append('Condition')


if not is_model_registered('offer', 'Range'):
    class Range(AbstractRange):
        pass

    __all__.append('Range')


if not is_model_registered('offer', 'RangeProduct'):
    class RangeProduct(AbstractRangeProduct):
        pass

    __all__.append('RangeProduct')


if not is_model_registered('offer', 'RangeProductFileUpload'):
    class RangeProductFileUpload(AbstractRangeProductFileUpload):
        pass

    __all__.append('RangeProductFileUpload')


# Import the benefits and the conditions. Required after initializing the
# parent models to allow overriding them

from oscar.apps.offer.benefits import *  # noqa isort:skip
from oscar.apps.offer.conditions import *  # noqa isort:skip

from oscar.apps.offer.benefits import __all__ as benefit_classes  # noqa isort:skip
from oscar.apps.offer.conditions import __all__ as condition_classes  # noqa isort:skip

__all__.extend(benefit_classes)
__all__.extend(condition_classes)

donnyji/oscar/apps/order/models.py
from oscar.apps.address.abstract_models import (
    AbstractBillingAddress, AbstractShippingAddress)
from oscar.apps.order.abstract_models import *  # noqa
from oscar.core.loading import is_model_registered

__all__ = ['PaymentEventQuantity', 'ShippingEventQuantity']


if not is_model_registered('order', 'Order'):
    class Order(AbstractOrder):
        pass

    __all__.append('Order')


if not is_model_registered('order', 'OrderNote'):
    class OrderNote(AbstractOrderNote):
        pass

    __all__.append('OrderNote')


if not is_model_registered('order', 'OrderStatusChange'):
    class OrderStatusChange(AbstractOrderStatusChange):
        pass

    __all__.append('OrderStatusChange')


if not is_model_registered('order', 'CommunicationEvent'):
    class CommunicationEvent(AbstractCommunicationEvent):
        pass

    __all__.append('CommunicationEvent')


if not is_model_registered('order', 'ShippingAddress'):
    class ShippingAddress(AbstractShippingAddress):
        pass

    __all__.append('ShippingAddress')


if not is_model_registered('order', 'BillingAddress'):
    class BillingAddress(AbstractBillingAddress):
        pass

    __all__.append('BillingAddress')


if not is_model_registered('order', 'Line'):
    class Line(AbstractLine):
        pass

    __all__.append('Line')


if not is_model_registered('order', 'LinePrice'):
    class LinePrice(AbstractLinePrice):
        pass

    __all__.append('LinePrice')


if not is_model_registered('order', 'LineAttribute'):
    class LineAttribute(AbstractLineAttribute):
        pass

    __all__.append('LineAttribute')


if not is_model_registered('order', 'ShippingEvent'):
    class ShippingEvent(AbstractShippingEvent):
        pass

    __all__.append('ShippingEvent')


if not is_model_registered('order', 'ShippingEventType'):
    class ShippingEventType(AbstractShippingEventType):
        pass

    __all__.append('ShippingEventType')


if not is_model_registered('order', 'PaymentEvent'):
    class PaymentEvent(AbstractPaymentEvent):
        pass

    __all__.append('PaymentEvent')


if not is_model_registered('order', 'PaymentEventType'):
    class PaymentEventType(AbstractPaymentEventType):
        pass

    __all__.append('PaymentEventType')


if not is_model_registered('order', 'OrderDiscount'):
    class OrderDiscount(AbstractOrderDiscount):
        pass

    __all__.append('OrderDiscount')

donnyji/oscar/apps/partner/models.py
from oscar.apps.address.abstract_models import AbstractPartnerAddress
from oscar.apps.partner.abstract_models import (
    AbstractPartner, AbstractStockAlert, AbstractStockRecord)
from oscar.core.loading import is_model_registered

__all__ = []


if not is_model_registered('partner', 'Partner'):
    class Partner(AbstractPartner):
        pass

    __all__.append('Partner')


if not is_model_registered('partner', 'PartnerAddress'):
    class PartnerAddress(AbstractPartnerAddress):
        pass

    __all__.append('PartnerAddress')


if not is_model_registered('partner', 'StockRecord'):
    class StockRecord(AbstractStockRecord):
        pass

    __all__.append('StockRecord')


if not is_model_registered('partner', 'StockAlert'):
    class StockAlert(AbstractStockAlert):
        pass

    __all__.append('StockAlert')

donnyji/oscar/apps/payment/models.py
from oscar.core.loading import is_model_registered

from . import abstract_models

__all__ = []


if not is_model_registered('payment', 'Transaction'):
    class Transaction(abstract_models.AbstractTransaction):
        pass

    __all__.append('Transaction')


if not is_model_registered('payment', 'Source'):
    class Source(abstract_models.AbstractSource):
        pass

    __all__.append('Source')


if not is_model_registered('payment', 'SourceType'):
    class SourceType(abstract_models.AbstractSourceType):
        pass

    __all__.append('SourceType')


if not is_model_registered('payment', 'Bankcard'):
    class Bankcard(abstract_models.AbstractBankcard):
        pass

    __all__.append('Bankcard')

donnyji/oscar/apps/shipping/models.py
from oscar.apps.shipping import abstract_models
from oscar.core.loading import is_model_registered

__all__ = []


if not is_model_registered('shipping', 'OrderAndItemCharges'):
    class OrderAndItemCharges(abstract_models.AbstractOrderAndItemCharges):
        pass

    __all__.append('OrderAndItemCharges')


if not is_model_registered('shipping', 'WeightBased'):
    class WeightBased(abstract_models.AbstractWeightBased):
        pass

    __all__.append('WeightBased')


if not is_model_registered('shipping', 'WeightBand'):
    class WeightBand(abstract_models.AbstractWeightBand):
        pass

    __all__.append('WeightBand')

donnyji/oscar/apps/voucher/models.py
from oscar.apps.voucher.abstract_models import (
    AbstractVoucher, AbstractVoucherApplication, AbstractVoucherSet)
from oscar.core.loading import is_model_registered

__all__ = []

if not is_model_registered('voucher', 'VoucherSet'):
    class VoucherSet(AbstractVoucherSet):
        pass

    __all__.append('VoucherSet')


if not is_model_registered('voucher', 'Voucher'):
    class Voucher(AbstractVoucher):
        pass

    __all__.append('Voucher')


if not is_model_registered('voucher', 'VoucherApplication'):
    class VoucherApplication(AbstractVoucherApplication):
        pass

    __all__.append('VoucherApplication')

donnyji/oscar/templates/oscar/dashboard/vouchers/voucher_delete.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% blocktrans with name=voucher.name %}Delete voucher '{{ name }}'?{% endblocktrans %} | {% trans "Vouchers" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-list' %}">{% trans "Vouchers" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-stats' pk=voucher.pk %}">{{ voucher }}</a>
        </li>
        <li class="active">{% trans "Delete?" %}</li>
    </ul>
{% endblock %}

{% block headertext %}
    {% blocktrans with name=voucher.name %}Delete voucher '{{ name }}'?{% endblocktrans %}
{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Voucher details" %}</h2>
    </div>
    <div class="well">
        <table class="table table-striped table-bordered table-hover">
            <tbody>
                <tr><th>{% trans "Name" %}</th><td>{{ voucher.name }}</td></tr>
                <tr><th>{% trans "Code" %}</th><td>{{ voucher.code }}</td></tr>
                <tr><th>{% trans "Start datetime" %}</th><td>{{ voucher.start_datetime }}</td></tr>
                <tr><th>{% trans "End datetime" %}</th><td>{{ voucher.end_datetime }}</td></tr>
                <tr><th>{% trans "Usage" %}</th><td>{{ voucher.usage }}</td></tr>
                <tr><th>{% trans "Discount" %}</th><td>{{ voucher.benefit.description|safe }}</td></tr>
            </tbody>
        </table>
        <form method="post">
            {% csrf_token %}
            <div class="form-actions">
                <button class="btn btn-danger btn-lg" type="submit" data-loading-text="{% trans 'Deleting...' %}">{% trans "Delete" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:voucher-list' %}">{% trans "cancel" %}</a>
            </div>
        </form>
    </div>
{% endblock dashboard_content %}

donnyji/oscar/templates/oscar/dashboard/vouchers/voucher_detail.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block title %}
    {{ voucher }} | {% trans "Vouchers" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-list' %}">{% trans "Vouchers" %}</a>
        </li>
        <li class="active">{{ voucher }}</li>
    </ul>
{% endblock %}

{% block headertext %}
    {{ voucher }}
{% endblock %}

{% block dashboard_content %}

    <div class="table-header">
        <h2>{% trans "Voucher details" %}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tbody>
            <tr><th>{% trans "Name" %}</th><td>{{ voucher.name }}</td></tr>
            <tr><th>{% trans "Code" %}</th><td>{{ voucher.code }}</td></tr>
            <tr><th>{% trans "Start datetime" %}</th><td>{{ voucher.start_datetime }}</td></tr>
            <tr><th>{% trans "End datetime" %}</th><td>{{ voucher.end_datetime }}</td></tr>
            <tr><th>{% trans "Usage" %}</th><td>{{ voucher.get_usage_display }}</td></tr>
            <tr><th>{% trans "Discount" %}</th><td>{{ voucher.benefit.description|safe }}</td></tr>
        </tbody>
    </table>

    <div class="table-header">
        <h2>{% trans "Voucher performance" %}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tbody>
            <tr><th>{% trans "Number of basket additions" %}</th><td>{{ voucher.num_basket_additions }}</td></tr>
            <tr><th>{% trans "Number of orders" %}</th><td>{{ voucher.num_orders }}</td></tr>
            <tr><th>{% trans "Total discount" %}</th><td>{{ voucher.total_discount|currency }}</td></tr>
        </tbody>
    </table>

    <div class="table-header">
        <h2>{% trans "Recent orders" %}</h2>
    </div>

    <table class="table table-striped table-bordered table-hover">
        {% if not discounts %}
            <tr><td>{% trans "No orders have been placed that use this voucher." %}</td></tr>
        {% else %}
            <thead>
                <tr>
                    <th>{% trans "Order number" %}</th>
                    <th>{% trans "Order total" %}</th>
                    <th>{% trans "Discount" %}</th>
                    <th>{% trans "Date placed" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for discount in discounts %}
                    {% with order=discount.order %}
                        <tr>
                            <td><a href="{% url "dashboard:order-detail" number=order.number %}">{{ order.number }}</a></td>
                            <td>{{ order.total_incl_tax|currency:order.currency }}</td>
                            <td>{{ discount.amount|currency:order.currency }}</td>
                            <td>{{ order.date_placed }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        {% endif %}
    </table>

    <div class="form-actions">
        <a class="btn btn-primary" href="{% url 'dashboard:voucher-update' pk=voucher.id %}">{% trans "Edit" %}</a> {% trans "or" %}
        <a class="btn btn-danger" href="{% url 'dashboard:voucher-delete' pk=voucher.id %}">{% trans "Delete" %}</a> {% trans "or" %}
        <a href="{% url 'dashboard:voucher-list' %}">{% trans "cancel" %}</a>
    </div>

{% endblock dashboard_content %}

donnyji/oscar/templates/oscar/dashboard/vouchers/voucher_form.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {{ title }} | {% trans "Vouchers" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-list' %}">{% trans "Vouchers" %}</a>
        </li>
        {% if voucher %}
        <li>
            <a href="{% url 'dashboard:voucher-stats' pk=voucher.id %}">{{ voucher }}</a>
        </li>
    {% endif %}
    <li class="active">{% trans "Edit" %}</li>
    </ul>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="icon-money icon-large"></i>
            {% if voucher %}
                {% trans "Edit voucher" %}
            {% else %}
                {% trans "Create voucher" %}
            {% endif %}
        </h2>
    </div>
    <form method="post" class="well form-stacked">
        {% csrf_token %}
        {% include "oscar/dashboard/partials/form_fields.html" with form=form %}
        {% block form_actions %}
            <div class="form-actions">
                <button class="btn btn-primary btn-lg" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:voucher-list' %}">{% trans "cancel" %}</a>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}

donnyji/oscar/templates/oscar/dashboard/vouchers/voucher_set_detail.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load sorting_tags %}
{% load i18n %}

{% block title %}
    {{ description }} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-set-list' %}">{% trans "Voucher sets" %}</a>
        </li>
        <li class="active">{{ description }}</li>
    </ul>
{% endblock %}

{% block header %}
<div class="page-header">
    <div class="pull-right">
    <a href="{% url 'dashboard:voucher-set-update' pk=voucher_set.pk %}" class="btn btn-primary btn-large "><i class="icon-plus"></i> {% trans "Update voucher set" %}</a>
    <a href="{% url 'dashboard:voucher-set-download' pk=voucher_set.pk %}" class="btn btn-primary btn-large "><i class="icon-plus"></i> {% trans "Download CSV" %}</a>
    </div>
    <h1>{% trans "Voucher set" %} '{{ voucher_set.name }}'</h1>
</div>
{% endblock header %}


{% block dashboard_content %}
<table class="table table-striped table-bordered">
    <caption>
        <h3>
            {% trans "Voucher set" %}
        </h3>
    </caption>
    <tbody>
        <tr>
            <th>{% trans "Title" %}</th>
            <td>{{ voucher_set.name }}</td>
        </tr>
        <tr>
            <th>{% trans "Start" %}</th>
            <td>{{ voucher_set.start_datetime }}</td>
        </tr>
        <tr>
            <th>{% trans "End" %}</th>
            <td>{{ voucher_set.end_datetime }}</td>
        </tr>
        <tr>
            <th>{% trans "Description" %}</th>
            <td>{{ voucher_set.description }}</td>
        </tr>
        <tr>
            <th>{% trans "Number of vouchers" %}</th>
            <td>{{ voucher_set.count }}</td>
        </tr>
        <tr>
            <th>{% trans "Created" %}</th>
            <td>{{ voucher_set.date_created }}</td>
        </tr>
    </tbody>
</table>

<div class="table-header">
    <h3><i class="icon-search icon-large"></i>{% trans "Search" %}</h3>
</div>
<div class="well">
    <form method="get" class="form-inline">
		{% include 'oscar/partials/form_fields_inline.html' with form=form %}
		<button type="submit" class="btn btn-primary">{% trans "Search" %}</button>
		<a href="{% url 'dashboard:voucher-list' %}" class="btn">{% trans "Reset" %}</a>
    </form>
</div>

<table class="table table-striped table-bordered table-hover">
    {% if description != "All vouchers" %}
        <caption><i class="icon-money icon-large"></i>{{ description }}</caption>
    {% endif %}
    {% if vouchers %}
    <tr>
        <th>{% trans "Code" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% anchor 'num_basket_additions' _("Num baskets") %}</th>
        <th>{% anchor 'num_orders' _("Num orders") %}</th>
        <th>{% anchor 'date_created' _("Date created") %}</th>
        <th></th>
    </tr>
        {% for voucher in vouchers %}
        <tr>
            <td>
                <span class="label label-default">{{ voucher.code }}</span>
            </td>
            <td>
                {% if voucher.is_active %}
                    <span class="label label-success">{% trans "Active" %}</span>
                {% else %}
                    <span class="label label-danger">{% trans "Inactive" %}</span>
                {% endif %}
            </td>
            <td>{{ voucher.num_basket_additions }}</td>
            <td>{{ voucher.num_orders }}</td>
            <td>{{ voucher.date_created }}</td>
            <td>
                <div class="btn-toolbar">
                    <div class="btn-group">
                      <button class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        {% trans "Actions" %}
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu pull-right">
                          <li><a href="{% url 'dashboard:voucher-stats' pk=voucher.id %}">{% trans "Stats" %}</a></li>
                          <li><a href="{% url 'dashboard:voucher-delete' pk=voucher.id %}">{% trans "Delete" %}</a></li>
                      </ul>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
    {% else %}
    <tr><td>{% trans "No vouchers found." %}</td></tr>
    {% endif %}
</table>
{% include "oscar/partials/pagination.html" %}
{% endblock dashboard_content %}

donnyji/oscar/templates/oscar/dashboard/vouchers/voucher_set_form.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {{ title }} | {% trans "Voucher sets" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-list' %}">{% trans "Voucher sets" %}</a>
        </li>
        {% if voucher %}
        <li>
            <a href="{% url 'dashboard:voucher-set' pk=voucher.id %}">{{ voucher }}</a>
        </li>
    {% endif %}
    <li class="active">{% trans "Edit" %}</li>
    </ul>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="icon-money icon-large"></i>
            {% if voucher %}
                {% trans "Edit voucher" %}
            {% else %}
                {% trans "Create voucher" %}
            {% endif %}
        </h2>
    </div>
    <form method="post" class="well form-stacked">
        {% csrf_token %}
        {% include "oscar/dashboard/partials/form_fields.html" with form=form %}
        {% block form_actions %}
            <div class="form-actions">
                <button class="btn btn-primary btn-large" type="submit">{% trans "Save" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:voucher-set-list' %}">{% trans "cancel" %}</a>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}